# Generated by Django 5.2.17 on 2026-10-05 20:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('routes', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.driverprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.route')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='schools.school')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TripStopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('APPROACHING_ALERT', 'Bus Approaching Alert'), ('ARRIVED', 'Bus Arrived at Stop'), ('DEPARTED', 'Bus Departed Stop')], max_length=25)),
                ('occurred_at', models.DateTimeField()),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routestop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_events', to='tracking.trip')),
            ],
            options={
                'unique_together': {('trip', 'route_stop', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed_kph', models.FloatField(blank=True, null=True)),
                ('accuracy_meters', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', '-recorded_at'], name='tracking_ve_trip_id_b3e6ed_idx')],
            },
        ),
    ]
