# Generated by Django 5.2.18 on 2026-10-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_vehiclelocation_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstopevent',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tripstopevent',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('CHILD_ABSENT', 'Student Absent / Called Ahead'), ('ROAD_BLOCKAGE', 'Road Blockage / Inaccessible'), ('GUARDIAN_DIRECT_PICKUP', 'Picked Up Directly by Parent'), ('SAFETY_CONCERN', 'Safety / Emergency Hazard'), ('OTHER', 'Other / Operational Decision')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tripstopevent',
            name='event_type',
            field=models.CharField(choices=[('APPROACHING_ALERT', 'Bus Approaching Alert'), ('ARRIVED', 'Bus Arrived at Stop'), ('DEPARTED', 'Bus Departed Stop'), ('SKIPPED', 'Stop Skipped')], max_length=25),
        ),
    ]
